on: [push, pull_request]

jobs:
    template-sync:
        if: github.repository == 'beyourahi/storefront_002'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2 # important!
            - uses: ahmadnassri/action-template-repository-sync@v2
              with:
                  github-token: ${{ secrets.SYNC_TOKEN }}
                  dry-run: false
